export type DashboardStat = {
  title: string;
  value: string;
  trend: string;
  positive: boolean;
  label: string;
};

export type RecentPatient = {
  id: number;
  name: string;
  age: number;
  gender: string;
  lastVisit: string;
};

export type RecentReport = {
  id: number;
  filename: string;
  uploadedAt: string;
  status: "Completed" | "Pending" | "Review";
};

export type RecentPrediction = {
  id: number;
  patient: string;
  disease: string;
  risk: "Low" | "Moderate" | "High";
  confidence: string;
  date: string;
};

export type SystemStatusItem = {
  service: string;
  status: "Online" | "Degraded" | "Offline";
  description: string;
};

export type ActivityEvent = {
  id: number;
  title: string;
  description: string;
  time: string;
};

export type PieSlice = {
  name: string;
  value: number;
};

export type LinePoint = {
  month: string;
  predictions: number;
  reports: number;
};

export type BarSlice = {
  category: string;
  value: number;
};

export type AreaData = {
  month: string;
  generated: number;
};

export async function getDashboardStats(): Promise<DashboardStat[]> {
  // TODO: Replace mock values with a backend dashboard summary endpoint.
  return [
    { title: "Total Patients", value: "1,248", trend: "+6.2%", positive: true, label: "Month over month" },
    { title: "AI Reports Generated", value: "892", trend: "+11%", positive: true, label: "Last 30 days" },
    { title: "Total Disease Predictions", value: "3,450", trend: "+8%", positive: true, label: "Autogenerated" },
    { title: "Disease Models Available", value: "9", trend: "Stable", positive: true, label: "Clinical catalog" },
    { title: "High Risk Cases", value: "18", trend: "-1", positive: false, label: "Current day" },
    { title: "OCR Reports Processed", value: "1,140", trend: "+25%", positive: true, label: "This month" },
  ];
}

export async function getRecentPatients(): Promise<RecentPatient[]> {
  // TODO: Replace mock values with patient registry endpoint.
  return [
    { id: 1, name: "Ava Chen", age: 46, gender: "Female", lastVisit: "2026-07-30" },
    { id: 2, name: "Ethan Patel", age: 62, gender: "Male", lastVisit: "2026-08-01" },
    { id: 3, name: "Mila Johnson", age: 35, gender: "Female", lastVisit: "2026-07-28" },
    { id: 4, name: "Noah Kim", age: 54, gender: "Male", lastVisit: "2026-08-02" },
  ];
}

export async function getRecentReports(): Promise<RecentReport[]> {
  // TODO: Replace mock values with report management endpoint.
  return [
    { id: 1, filename: "admission_notes_415.pdf", uploadedAt: "2026-08-02", status: "Completed" },
    { id: 2, filename: "ct_head_scan_7-31.pdf", uploadedAt: "2026-08-01", status: "Review" },
    { id: 3, filename: "labs_2026-07-29.csv", uploadedAt: "2026-07-29", status: "Completed" },
    { id: 4, filename: "echo_report_220.pdf", uploadedAt: "2026-07-28", status: "Pending" },
  ];
}

export async function getRecentPredictions(): Promise<RecentPrediction[]> {
  // TODO: Replace mock values with prediction history endpoint.
  return [
    { id: 1, patient: "Ava Chen", disease: "Diabetes", risk: "High", confidence: "92%", date: "2026-08-02" },
    { id: 2, patient: "Liam Garcia", disease: "Stroke", risk: "Moderate", confidence: "78%", date: "2026-08-01" },
    { id: 3, patient: "Sophia Williams", disease: "Kidney", risk: "Low", confidence: "66%", date: "2026-07-31" },
    { id: 4, patient: "Mason Brown", disease: "Heart Failure", risk: "Moderate", confidence: "81%", date: "2026-07-30" },
  ];
}

export async function getSystemStatus(): Promise<SystemStatusItem[]> {
  // TODO: Replace mock values with live service health endpoint.
  return [
    { service: "Backend API", status: "Online", description: "API is responding normally." },
    { service: "Database", status: "Online", description: "Primary instance is healthy." },
    { service: "OCR Service", status: "Degraded", description: "Queued jobs are processing with mild delay." },
    { service: "AI Models Loaded", status: "Online", description: "All models are available." },
    { service: "Knowledge Base", status: "Online", description: "Search index is synchronized." },
    { service: "Authentication", status: "Online", description: "Session validation is healthy." },
  ];
}

export async function getPredictionDistribution(): Promise<PieSlice[]> {
  // TODO: Replace mock values with prediction distribution endpoint.
  return [
    { name: "Heart Disease", value: 24 },
    { name: "Diabetes", value: 18 },
    { name: "Kidney", value: 12 },
    { name: "Liver", value: 8 },
    { name: "Breast Cancer", value: 10 },
    { name: "Parkinson's", value: 6 },
    { name: "Hepatitis", value: 7 },
    { name: "Heart Failure", value: 9 },
    { name: "Stroke", value: 6 },
  ];
}

export async function getMonthlyPredictions(): Promise<LinePoint[]> {
  return [
    { month: "Jan", predictions: 310, reports: 180 },
    { month: "Feb", predictions: 340, reports: 200 },
    { month: "Mar", predictions: 380, reports: 220 },
    { month: "Apr", predictions: 420, reports: 240 },
    { month: "May", predictions: 470, reports: 280 },
    { month: "Jun", predictions: 530, reports: 310 },
    { month: "Jul", predictions: 590, reports: 345 },
    { month: "Aug", predictions: 610, reports: 360 },
  ];
}

export async function getRiskDistribution(): Promise<BarSlice[]> {
  return [
    { category: "Low", value: 42 },
    { category: "Moderate", value: 28 },
    { category: "High", value: 18 },
    { category: "Critical", value: 12 },
  ];
}

export async function getReportsAreaData(): Promise<AreaData[]> {
  return [
    { month: "Jan", generated: 120 },
    { month: "Feb", generated: 150 },
    { month: "Mar", generated: 180 },
    { month: "Apr", generated: 210 },
    { month: "May", generated: 250 },
    { month: "Jun", generated: 290 },
    { month: "Jul", generated: 330 },
    { month: "Aug", generated: 360 },
  ];
}
